service: sls-accessory

custom: 
  secret: ${file(secret.json)}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.secret.STAGE}
  region: us-east-1
  environment: 
    STAGE: ${self:custom.secret.STAGE}
    DB: ${self:custom.secret.DB}
    JWT_SECRET: ${self:custom.secret.JWT_SECRET}
    COOKIEEXPIRE: ${self:custom.secret.COOKIEEXPIRE}
    SEND_GRID_API_KEY: ${self:custom.secret.SEND_GRID_API_KEY}
    
functions:
  app:
    handler: handler.app
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-offline